# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 
target 'icebox' do
 use_frameworks!
 pod 'Alamofire', '~> 4.3'
 pod 'Charts'
 pod 'ChartsRealm'
 pod 'PusherSwift'
 pod 'PushNotifications'
 pod 'NotificationBannerSwift'
end